using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Interactivity;
using Operations.Classification.WpfUi.Technical.Converters;

namespace Operations.Classification.WpfUi.Technical.Controls
{
    public class CustomizeAutoGeneratedColumnsBehavior : Behavior<DataGrid>
    {
        protected override void OnAttached()
        {
            base.OnAttached();
            AssociatedObject.AutoGeneratingColumn += AssociatedObjectAutoGeneratingColumn;
        }

        protected override void OnDetaching()
        {
            AssociatedObject.AutoGeneratingColumn -= AssociatedObjectAutoGeneratingColumn;
            base.OnDetaching();
        }

        private void AssociatedObjectAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var desc = e.PropertyDescriptor as PropertyDescriptor;
            var displayAttribute = desc?.Attributes[typeof(DisplayAttribute)] as DisplayAttribute;
            if (displayAttribute?.AutoGenerateField == false)
            {
                e.Cancel = true;
                return;
            }

            var boundColumn = e.Column as DataGridBoundColumn;
            var dtc = boundColumn as DataGridTextColumn;

            if (desc?.Attributes[typeof(DisplayFormatAttribute)] is DisplayFormatAttribute displayFormatAttribute)
            {
                if (dtc != null)
                {
                    var bindingBase = dtc.Binding;
                    var binding = bindingBase as Binding;
                    if (!string.IsNullOrEmpty(displayFormatAttribute.DataFormatString))
                    {
                        bindingBase.StringFormat = displayFormatAttribute.DataFormatString;
                        const string CurrencyFormat = ":C";
                        if (dtc.Binding.StringFormat.Contains(CurrencyFormat))
                        {
                            if (binding != null && binding.Converter == null)
                            {
                                binding.Converter = DefaultAmountValueConverter.Instance;
                            }
                        }
                    }

                    if (!string.IsNullOrEmpty(displayFormatAttribute.NullDisplayText))
                    {
                        bindingBase.TargetNullValue = displayFormatAttribute.NullDisplayText;
                    }
                }
            }
        }
    }
}