using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Windows.Controls;
using System.Windows.Interactivity;

namespace Operations.Classification.WpfUi.Technical.Controls
{
    public class CustomizeAutoGeneratedColumnsBehavior : Behavior<DataGrid>
    {
        protected override void OnAttached()
        {
            base.OnAttached();
            AssociatedObject.AutoGeneratingColumn += AssociatedObject_AutoGeneratingColumn;
        }

        private void AssociatedObject_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var desc = e.PropertyDescriptor as PropertyDescriptor;
            var displayAttribute = desc?.Attributes[typeof(DisplayAttribute)] as DisplayAttribute;
            if (displayAttribute?.AutoGenerateField == false)
            {
                e.Cancel = true;
            }

            var boundColumn = e.Column as DataGridBoundColumn;
            var dtc = boundColumn as DataGridTextColumn;

            var displayFormatAttribute = desc?.Attributes[typeof(DisplayFormatAttribute)] as DisplayFormatAttribute;
            if (displayFormatAttribute != null)
            {
                if (dtc!=null)
                {
                    if (!string.IsNullOrEmpty(displayFormatAttribute.DataFormatString))
                    {
                        dtc.Binding.StringFormat = displayFormatAttribute.DataFormatString;
                    }
                    if (!string.IsNullOrEmpty(displayFormatAttribute.NullDisplayText))
                    {
                        dtc.Binding.TargetNullValue = displayFormatAttribute.NullDisplayText;
                    }
                }
            }
        }

        protected override void OnDetaching()
        {
            AssociatedObject.AutoGeneratingColumn -= AssociatedObject_AutoGeneratingColumn;
            base.OnDetaching();
        }
    }
}