//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Classification.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Operations.Classification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;CartPayment&quot;,
        ///    &quot;SourceKind&quot;: &quot;FortisCsvArchive&quot;,
        ///    &quot;Expression&quot;: { &quot;Note&quot;: &quot;^PAIEMENT PAR CARTE DE BANQUE.{59}XXXX X[0-9]{3} [0-9] (?&lt;ThirdPartyThenCity&gt;.*) [0-9]{2}\\/[0-9]{2}\\/[0-9]{4}.*DATE VALEUR : [0-9]{2}\\/[0-9]{2}\\/[0-9]{4}$&quot; }
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;CartPayment&quot;,
        ///    &quot;SourceKind&quot;: &quot;FortisCsvExport&quot;,
        ///    &quot;Expression&quot;: { &quot;Note&quot;: &quot;^AVEC LA CARTE.{11}XXXX X[0-9]{3} [0-9] (?&lt;ThirdPartyThenCity&gt;.*?)([0-9]{2}-[0-9]{2}-[0-9]{4}.*|EXECUTE|DATE VALEUR|$)&quot; }
        ///  },
        ///  {
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FortisUnifiedAccountPatternMappings {
            get {
                return ResourceManager.GetString("FortisUnifiedAccountPatternMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;WOLUWE-SAINT-LAMBERT&quot;,
        ///    &quot;Abbrevs&quot;: [ &quot;WOLUWE SA&quot;, &quot;1200 BRUX&quot;, &quot;1200 BRUSS&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;LIEGE&quot;,
        ///    &quot;Abbrevs&quot;: [ &quot;LIEGE GAL&quot;, &quot;LIEGE OUT&quot;, &quot;LIEGE 2&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;CHAUDFONTAINE&quot;,
        ///    &quot;Abbrevs&quot;: [ &quot;CHAUDFONT&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;FRANCORCHAMPS&quot;,
        ///    &quot;Abbrevs&quot;: [ &quot;FRANCORCH&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;BRAINE L&apos;ALLEUD&quot;,
        ///    &quot;Abbrevs&quot;: [ &quot;BRAINE AL&quot;, &quot;BRAINE L&apos;&quot;, &quot;BRAINE-L&apos;ALLEU&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;LA LOUVIERE&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;BEAUF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;BankTransfert&quot;,
        ///    &quot;SourceKind&quot;: &quot;SodexoCsvExport&quot;,
        ///    &quot;Expression&quot;: { &quot;Note&quot;: &quot;^(?&lt;Communication&gt;Versement de [0-9]+ eLunch Pass d&apos;une valeur de [0-9\\.]+ €) de (?&lt;ThirdParty&gt;.+)$&quot; }
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;CartPayment&quot;,
        ///    &quot;SourceKind&quot;: &quot;SodexoCsvExport&quot;,
        ///    &quot;Expression&quot;: { &quot;Note&quot;: &quot;^Dépense (?&lt;ThirdPartyThenCity&gt;.+)\\(Transaction \\d+\\)$&quot; }
        ///  }
        ///].
        /// </summary>
        internal static string SodexoUnifiedAccountPatternMappings {
            get {
                return ResourceManager.GetString("SodexoUnifiedAccountPatternMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal,Localité,Sous-commune,Province,Langue
        ///2970,&apos;S Gravenwezel,Oui,Anvers,FR_BE
        ///3700,&apos;S Herenelderen,Oui,Limbourg,FR_BE
        ///7510,3 Suisses,,,FR_BE
        ///9420,Aaigem,Oui,Flandre-Orientale,FR_BE
        ///8511,Aalbeke,Oui,Flandre-Occidentale,FR_BE
        ///3800,Aalst,Oui,Limbourg,FR_BE
        ///9300,AALST,Non,Flandre-Orientale,FR_BE
        ///9880,AALTER,Non,Flandre-Orientale,FR_BE
        ///3200,AARSCHOT,Non,Brabant Flamand,FR_BE
        ///8700,Aarsele,Oui,Flandre-Occidentale,FR_BE
        ///8211,Aartrijke,Oui,Flandre-Occidentale,FR_BE
        ///2630,AARTSELAAR,Non,Anvers,FR_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zipcodes_alpha_beligum {
            get {
                return ResourceManager.GetString("zipcodes_alpha_beligum", resourceCulture);
            }
        }
    }
}
