// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Operations.Classification.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Unify Fortis Operations Export details")]
    [NUnit.Framework.CategoryAttribute("UnitTest")]
    public partial class UnifyFortisOperationsExportDetailsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UnifyFortisExport.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Unify Fortis Operations Export details", "\tIn order to classify my personal operations,\r\n\tI want a more structure operation" +
                    " detail for my fortis transaction exports", ProgrammingLanguage.CSharp, new string[] {
                        "UnitTest"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("parse fortis amounts")]
        public virtual void ParseFortisAmounts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("parse fortis amounts", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Amount"});
            table1.AddRow(new string[] {
                        "VE1",
                        "0,01"});
            table1.AddRow(new string[] {
                        "VE2",
                        "-0,01"});
#line 7
 testRunner.Given("I have read the following fortis operations from export files", ((string)(null)), table1, "Given ");
#line 12
 testRunner.When("I unify and transform the read operations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationId",
                        "Income",
                        "Outcome"});
            table2.AddRow(new string[] {
                        "VE1",
                        "0.01",
                        "0"});
            table2.AddRow(new string[] {
                        "VE2",
                        "0",
                        "0.01"});
#line 14
 testRunner.Then("the operations data is", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("parse \'BankTransfert\'")]
        public virtual void ParseBankTransfert()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("parse \'BankTransfert\'", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Detail"});
            table3.AddRow(new string[] {
                        "2017-0010",
                        "PROXIMUS MOBILE BE31435411161155BIC KREDBEBB    VIA MOBILE BANKING COMMUNICATION " +
                            ": 285293318632 EXECUTE LE 05-02 DATE VALEUR : 05/02/2017"});
            table3.AddRow(new string[] {
                        "2017-0020",
                        "GEVELCO BE05 3701 2392 6075  BIC BBRUBEBBCOMMUNICATION: LOYER RUE DE PASCALE 15 -" +
                            " ETAGE 1  BR AYE - BACQUELAINE DATE VALEUR : 01/02/2017"});
            table3.AddRow(new string[] {
                        "2017-0030",
                        "GEVELCO BE05370123926075BIC BBRUBEBB VOTRE REFERENCE : 171828956 COMMUNICATION : " +
                            "LOYER RUE DE PASCALE 15 - ETAGE 1  BR AYE - BACQUELAINE DATE VALEUR : 03/04/2017" +
                            ""});
            table3.AddRow(new string[] {
                        "2017-0040",
                        "PARTENAMUT BE40310083000663BIC BBRUBEBB    VIA WEB BANKING COMMUNICATION : 170010" +
                            "267366 DATE VALEUR : 23/01/2017"});
            table3.AddRow(new string[] {
                        "2017-0050",
                        "PARTENA - MUTUALITE LIBRE BE74 2100 0818 2307  BIC GEBABEBBREFERENCE DONNEUR D\'OR" +
                            "DRE : 5090411H691 COMMUNICATION : /C/ PAIE /0201733339803 DU 10/04/2017 POUR 001" +
                            " PRESTATIONS CHEZ M.BAYET BEN 0201733339803 711041707696 DATE VALEUR : 11/04/201" +
                            "7"});
            table3.AddRow(new string[] {
                        "2017-0060",
                        "SELLIGENT S.A. AVENUE DE FINLANDE, 21420        BRAINE-L\'ALLEU BE02 3600 9651 844" +
                            "0  BIC BBRUBEBB REFERENCE DONNEUR D\'ORDRE : 1CS0125-01-0000245-1701310102822878 " +
                            "COMMUNICATION : /A/ 1CS0125-01-0000245 DATE VALEUR : 13/01/2017"});
            table3.AddRow(new string[] {
                        "2017-0070",
                        "BACQUELAINE SYLVIE RUE DU DUC 231150     WOLUWE-SAINT-PIERRE BE70 0013 5026 1925 " +
                            " BIC GEBABEBB PAS DE COMMUNICATION DATE VALEUR : 18/01/2017"});
            table3.AddRow(new string[] {
                        "2017-0080",
                        "COLINE BRAYE BE89750668924185BIC AXABBE22    VIA WEB BANKING COMMUNICATION : ANNI" +
                            "F PAPA DATE VALEUR : 05/12/2016"});
#line 20
 testRunner.Given("I have read the following fortis operations from export files", ((string)(null)), table3, "Given ");
#line 31
 testRunner.When("I unify and transform the read operations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationId",
                        "ThirdParty",
                        "City",
                        "Address",
                        "PatternName",
                        "Communication",
                        "IBAN",
                        "BIC",
                        "ThirdPartyOperationRef"});
            table4.AddRow(new string[] {
                        "2017-0010",
                        "PROXIMUS MOBILE",
                        "",
                        "",
                        "BankTransfert",
                        "285293318632",
                        "BE31435411161155",
                        "KREDBEBB",
                        ""});
            table4.AddRow(new string[] {
                        "2017-0020",
                        "GEVELCO",
                        "",
                        "",
                        "BankTransfert",
                        "LOYER RUE DE PASCALE 15 - ETAGE 1  BR AYE - BACQUELAINE",
                        "BE05 3701 2392 6075",
                        "BBRUBEBB",
                        ""});
            table4.AddRow(new string[] {
                        "2017-0030",
                        "GEVELCO",
                        "",
                        "",
                        "BankTransfert",
                        "LOYER RUE DE PASCALE 15 - ETAGE 1  BR AYE - BACQUELAINE",
                        "BE05370123926075",
                        "BBRUBEBB",
                        "171828956"});
            table4.AddRow(new string[] {
                        "2017-0040",
                        "PARTENAMUT",
                        "",
                        "",
                        "BankTransfert",
                        "170010267366",
                        "BE40310083000663",
                        "BBRUBEBB",
                        ""});
            table4.AddRow(new string[] {
                        "2017-0050",
                        "PARTENA - MUTUALITE LIBRE",
                        "",
                        "",
                        "BankTransfert",
                        "/C/ PAIE /0201733339803 DU 10/04/2017 POUR 001 PRESTATIONS CHEZ M.BAYET BEN 02017" +
                            "33339803 711041707696",
                        "BE74 2100 0818 2307",
                        "GEBABEBB",
                        "5090411H691"});
            table4.AddRow(new string[] {
                        "2017-0060",
                        "SELLIGENT S.A.",
                        "BRAINE-L\'ALLEU",
                        "AVENUE DE FINLANDE, 21420",
                        "BankTransfert",
                        "/A/ 1CS0125-01-0000245",
                        "BE02 3600 9651 8440",
                        "BBRUBEBB",
                        "1CS0125-01-0000245-1701310102822878"});
            table4.AddRow(new string[] {
                        "2017-0070",
                        "BACQUELAINE SYLVIE",
                        "WOLUWE-SAINT-PIERRE",
                        "RUE DU DUC 231150",
                        "BankTransfert",
                        "",
                        "BE70 0013 5026 1925",
                        "GEBABEBB",
                        ""});
            table4.AddRow(new string[] {
                        "2017-0080",
                        "COLINE BRAYE",
                        "",
                        "",
                        "BankTransfert",
                        "ANNIF PAPA",
                        "BE89750668924185",
                        "AXABBE22",
                        ""});
#line 33
 testRunner.Then("the operations data is", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("parse \'CartPayment\'")]
        public virtual void ParseCartPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("parse \'CartPayment\'", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Detail"});
            table5.AddRow(new string[] {
                        "2017-0001",
                        "AVEC LA CARTE 6703 04XX XXXX X315 7 CARREFOUR EXPR   1000 BRUS.07-02-2017 EXECUTE" +
                            " LE 07-02 DATE VALEUR : 07/02/2017"});
            table5.AddRow(new string[] {
                        "2017-0002",
                        "AVEC LA CARTE 6703 04XX XXXX X600 0 CARREFOUR EXPRES  BRUXELLES31/08/2017 DATE VA" +
                            "LEUR : 31/08/2017"});
            table5.AddRow(new string[] {
                        "2017-0010",
                        "AVEC LA CARTE 6703 04XX XXXX X600 0 BEAUFAYS          BEAUFAYS19/08/2017 EXECUTE " +
                            "LE 19-08 DATE VALEUR : 19/08/2017"});
            table5.AddRow(new string[] {
                        "2017-0020",
                        "AVEC LA CARTE 6703 04XX XXXX X725 6 SNCB BXL          P2M MOBIL14-04-2017 EXECUTE" +
                            " LE 14-04 DATE VALEUR : 14/04/2017"});
            table5.AddRow(new string[] {
                        "2017-0021",
                        "AVEC LA CARTE 6703 04XX XXXX X725 6 INGENICO          P2M MOBIL14-08-2017 DATE VA" +
                            "LEUR : 14/08/2017"});
            table5.AddRow(new string[] {
                        "2017-0022",
                        "AVEC LA CARTE 6703 04XX XXXX X725 6 STEPH LAMPION      P2P MOBIL28-06-2017 DATE V" +
                            "ALEUR : 28/06/2017"});
#line 45
    testRunner.Given("I have read the following fortis operations from export files", ((string)(null)), table5, "Given ");
#line 53
 testRunner.When("I unify and transform the read operations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationId",
                        "ThirdParty",
                        "City",
                        "PatternName"});
            table6.AddRow(new string[] {
                        "2017-0001",
                        "CARREFOUR EXPR",
                        "BRUXELLES",
                        "CartPayment"});
            table6.AddRow(new string[] {
                        "2017-0002",
                        "CARREFOUR EXPRES",
                        "BRUXELLES",
                        "CartPayment"});
            table6.AddRow(new string[] {
                        "2017-0010",
                        "BEAUFAYS",
                        "BEAUFAYS",
                        "CartPayment"});
            table6.AddRow(new string[] {
                        "2017-0020",
                        "SNCB",
                        "BRUXELLES",
                        "CartPaymentP2M"});
            table6.AddRow(new string[] {
                        "2017-0021",
                        "INGENICO",
                        "",
                        "CartPaymentP2M"});
            table6.AddRow(new string[] {
                        "2017-0022",
                        "STEPH LAMPION",
                        "",
                        "CartPaymentP2P"});
#line 55
    testRunner.Then("the operations data is", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("parse \'Domiciliation\'")]
        public virtual void ParseDomiciliation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("parse \'Domiciliation\'", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Detail"});
            table7.AddRow(new string[] {
                        "2017-0001",
                        "PAYPAL EUROPE S.A.R.L. ET CIE S.C.A NUMERO DE MANDAT :43FJ224QUR62Q REFERENCE : 1" +
                            "000265758596 PAYPAL COMMUNICATION : 1000265758596 PAYPAL DATE VALEUR : 02/12/201" +
                            "6"});
#line 66
    testRunner.Given("I have read the following fortis operations from export files", ((string)(null)), table7, "Given ");
#line 70
 testRunner.When("I unify and transform the read operations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationId",
                        "ThirdParty",
                        "PatternName",
                        "Mandat",
                        "ThirdPartyOperationRef",
                        "Communication"});
            table8.AddRow(new string[] {
                        "2017-0001",
                        "PAYPAL EUROPE S.A.R.L. ET CIE S.C.A",
                        "Domiciliation",
                        "43FJ224QUR62Q",
                        "1000265758596 PAYPAL",
                        "1000265758596 PAYPAL"});
#line 72
    testRunner.Then("the operations data is", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("parse \'CreditPayment\'")]
        public virtual void ParseCreditPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("parse \'CreditPayment\'", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Detail"});
            table9.AddRow(new string[] {
                        "2017-0001",
                        "COMPTE INTERNE VISA : 17503879 ETAT DE DEPENSES NUMERO 336DATE VALEUR : 12/12/201" +
                            "6"});
#line 79
    testRunner.Given("I have read the following fortis operations from export files", ((string)(null)), table9, "Given ");
#line 83
 testRunner.When("I unify and transform the read operations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationId",
                        "ThirdParty",
                        "PatternName",
                        "Communication"});
            table10.AddRow(new string[] {
                        "2017-0001",
                        "17503879",
                        "CreditPayment",
                        "ETAT DE DEPENSES NUMERO 336"});
#line 85
 testRunner.Then("the operations data is", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("parse \'BankFees\'")]
        public virtual void ParseBankFees()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("parse \'BankFees\'", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Detail",
                        "CounterpartyOfTheTransaction"});
            table11.AddRow(new string[] {
                        "2017-0001",
                        "COMFORT PACK EXECUTE LE 06-02DATE VALEUR : 01/02/2017",
                        "ANY"});
            table11.AddRow(new string[] {
                        "2017-0002",
                        "PERIODE DU 01-02-2017 AU 28-02-2017DETAILS VOIR ANNEXE EXECUTE LE 07-03 DATE VALE" +
                            "UR : 01/03/2017",
                        "ANY"});
            table11.AddRow(new string[] {
                        "2017-0003",
                        "EXECUTE LE 07-03 DATE VALEUR : 01/03/2017",
                        "RECTIFICATION VERSEMENT BONUS"});
#line 91
    testRunner.Given("I have read the following fortis operations from export files", ((string)(null)), table11, "Given ");
#line 97
 testRunner.When("I unify and transform the read operations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationId",
                        "ThirdParty",
                        "PatternName",
                        "Communication"});
            table12.AddRow(new string[] {
                        "2017-0001",
                        "Fortis",
                        "BankFees",
                        "MONTHLY FEE COMFORT PACK"});
            table12.AddRow(new string[] {
                        "2017-0002",
                        "Fortis",
                        "BankFees",
                        "PERIODE DU 01-02-2017 AU 28-02-2017"});
            table12.AddRow(new string[] {
                        "2017-0003",
                        "Fortis",
                        "BankFees",
                        "RECTIFICATION VERSEMENT BONUS"});
#line 99
 testRunner.Then("the operations data is", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
